name: Push to remote repo on incoming push to this repo
on: [ push, workflow_dispatch ]
jobs:
  push-to-remote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of the personal access token.
          fetch-depth: 0  # otherwise, there would be errors pushing refs to the destination repository.
          ref: main
      - name: Push checked out repo to remote
        env:
          URL: ${{ secrets.REMOTE_URL }}
          PAT: ${{ secrets.REMOTE_PAT }}
        run: |
          echo "* On branch"
          echo "---"
          git branch --show-current
          echo "\n* List checked out contents of github repo"
          echo "---"
          ls -l
          echo "\n* Push main branch to remote repo"
          echo "---"
          git -c http.extraheader="Authorization: Basic $PAT" push --force $URL main
